# Logging configuration
# Controls how detailed the logs will be and what information is recorded
logging:
  level: INFO  # Controls log verbosity: DEBUG (most verbose), INFO, WARNING, ERROR, CRITICAL (least verbose)
  log_requests: false  # When true, logs API request and response details for troubleshooting API interactions

# Database configuration
# PostgreSQL database connection settings for storing account data and statistics
database:
  host: 0.0.0.0  # Database server hostname or IP address
  port: 5432  # PostgreSQL server port
  name: stork  # Database name
  user: postgres  # Database username
  password: 123456  # Database password

# Authentication configuration
auth:
  concurrent_operations: 1  # Number of parallel authorizations in batch mode
  delay_range: [15, 25]  # Min and max seconds to delay before authentication

# Farming configuration
farming:
  validation_workers: 10  # Number of simultaneous price validations
  token_refresh_workers: 10  # Number of simultaneous token refreshes
  update_stats_on_refresh: false  # Whether to update statistics during token refresh (may cause statistics overwrite)
  validation_delay: 3  # Base delay in seconds between account validations, increases exponentially for each account

# Statistics update configuration
stats_update:
  concurrent_operations: 1  # Number of parallel account statistics updates
  delay_range: [15, 20]  # Min and max seconds to delay before updating statistics

# Password reset configuration
password_reset:
  concurrent_operations: 1  # Number of parallel password reset operations
  delay_range: [15, 20]  # Min and max seconds to delay before password reset operations

# Registration configuration
registration:
  concurrent_operations: 1  # Number of parallel registration processes (affects registration speed)
  delay_range: [15, 20]  # Min and max seconds to delay before registration
  referral:
    mode: "static"  # Referral code selection mode: "random" - uses random codes from database, "static" - uses a fixed code
    static_code: "7A5NK0GPK5"  # The specific referral code to use when mode is set to "static"

# Email configuration
email:
  imap_mode: standard  # Email processing mode: "standard" (individual accounts),"redirect" (forwarded emails)
  imap_server: mail.adm.tools  # Default IMAP server when not specified by domain
  wait_seconds: 10  # Number of seconds to wait for verification emails to arrive
  attempt_pause: 5  # Pause duration in seconds between email check attempts
  max_attempts: 5  # Maximum number of attempts to check for verification emails before giving up
  
  # Redirect mode configuration (used when imap_mode is set to "redirect")
  redirect_email: "test@gmail.com"  # Email address for the redirect account where all verification emails are forwarded
  redirect_password: "wegrwgerhgerg"  # Password for the redirect account
  redirect_server: ""  # Custom IMAP server for redirect account (if empty, will use server based on email domain)

  # Domain-specific IMAP settings
  domain_servers:
    gmail.com:
      server: imap.gmail.com  # IMAP server for Gmail accounts
    outlook.com:
      server: outlook.office365.com  # IMAP server for Outlook accounts
    hotmail.com:
      server: outlook.office365.com  # IMAP server for Hotmail accounts
    yahoo.com:
      server: imap.mail.yahoo.com  # IMAP server for Yahoo accounts
    liteinbox.com:
      server: mail.adm.tools  # IMAP server for LiteInbox accounts
    # Add other domains as needed

# Proxy configuration
proxy:
  enabled: true  # Whether to use proxies for API requests
  rotate_on_waf: true  # Automatically rotate proxy when WAF (Web Application Firewall) block is detected
  rotate_on_connection_error: true  # Automatically rotate proxy when connection errors occur
  max_rotation_attempts: 3  # Number of times to try rotating proxy on connection error

# Settings for retry logic when errors occur
error_handling:
  max_retries: 5  # Maximum number of immediate retry attempts per cycle
  retry_delay_seconds: 2  # Delay in seconds between retry attempts
  retry_long_delay_minutes: 5  # Longer delay in minutes between retry cycles
  retry_cycles: 5  # Maximum number of retry cycles before giving up 
